# Arrays
Todo los objetos deben ser de la misma clase
Misma dimensiones

In [1]:
import numpy as np

In [7]:
a = np.array([[0,1,2,3],[4,5,6,7]]) #Iguales dimensiones
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [8]:
a.shape #Saber las dimensiones del array

(2, 4)

In [14]:
a[0,3] #Obtener un dato del array
a[0]

array([2])

In [11]:
a[0,3]=79 #Reemplazar valores
a

array([[ 0,  1,  2, 79],
       [ 4,  5,  6,  7]])

In [15]:
b = np.array([3,5])
b

array([3, 5])

# Random Numbers
random.random() : generates a random float in the range [0;1)]
random.randint() : genates over a provides interval and delivers an integer value
np.random.randint(1,6,(4,6)) #Matrices de numeros aleatorios

In [16]:
import random

In [18]:
prob = random.random()
print (prob)

0.7336867461257068


In [19]:
number = random.randint(1,6)
number

6

In [ ]:
import numpy as np

In [22]:
np.random.randint(1,6,(4,6)) #Matrices de numeros aleatorios

array([[5, 2, 2, 3, 1, 1],
       [2, 5, 2, 1, 1, 3],
       [1, 3, 1, 3, 5, 4],
       [1, 2, 1, 2, 3, 2]])